name: Deploy PostgreSQL Migrations

on:
  push:
    branches:
      - dev
    paths:
      - 'de-proj-1/flyway/**'  # Trigger only if files change in this path
  workflow_dispatch:  # Allow manual triggers

jobs:
  flyway-migration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: 5433
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}

      - name: Inject Secrets into flyway.conf
        run: |
          envsubst < flyway/flyway.template.conf > flyway/flyway.conf

      - name: Flyway Migration via Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/de-proj-1/flyway/migrations:/flyway/sql \
            -v ${{ github.workspace }}/de-proj-1/flyway/flyway.conf:/flyway/conf/flyway.conf \
            -e FLYWAY_USER=${{ secrets.DB_USER }} \
            -e FLYWAY_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=5433 \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            flyway/flyway:9.16.0 migrate

