name: Auto Deploy with Helm

on:
  push:
    branches:
      - dev
    paths:
      - helm/values.yaml  # Path to trigger only on values.yaml updates

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Helm Deploy Script
        run: |
          chmod +x ./bash/deploy_helm.sh
          ./bash/deploy_helm.sh

